handlers:
  - name: mysql-socket-fix 
    shell: echo run >> /root/hello
      sudomysql -uroot -e "update mysql.user set plugin='mysql_native_password' WHERE User='root';"
      mysql -uroot -e "update mysql.user set password='' WHERE User='root';"
      mysql -uroot -e "flush privileges"
    notify: update-root-user-password

  - name: update-root-user-password
    mysql_user:
      user: root
      password: abc123
    notify: update-root-my.cnf

  - name: update-root-my.cnf
    template:
      src: files/.my.cnf
      dest: /root/.my.cnf

  - name: mysql-restart
    service:
      name: mysql
      state: restarted

roles: 
  - name: "Installing MySQL"
    apt:
      pkg: mariadb-server-10.1
      state: present

  - name: "Installing PyMysql requirement"
    apt:
      name: python-pymysql
      state: present
    notify: 
     - mysql-socket-fix

  - name: "Bind to external port"
    ini_file:
      path: /etc/mysql/mariadb.conf.d/50-server.cnf
      section: mysqld
      option: bind-address
      value: 0.0.0.0
      backup: yes
    notify:
      - mysql-restart


  - name: "Create WP database"
    mysql_db:
          name: wordpress_db

  - name: "create mysql user for box1"
    mysql_user:
          host: 192.168.33.10
          user: wpuser
          password: wpuser_pass
          priv: 'wordpress_db.*:ALL'
          state: present

  - name: "create mysql user for box2"
    mysql_user:
          host: 192.168.33.20
          user: wpuser
          password: wpuser_pass
          priv: 'wordpress_db.*:ALL'
          state: present
